using System;

namespace WEB_APPLICATION.Models
{
    public class Assessment
    {
        public int assessmentId { get; set; }
        public int lessonId { get; set; }
        public int attemptNumber { get; set; }

        public Assessment(int assessmentId, int lessonId)
        {
            this.assessmentId = assessmentId;
            this.lessonId = lessonId;
            this.attemptNumber = 0;
        }
        // this a constructor to create an assessment only using the lessonId since the assessmentId is auto generated by the database( via Identity attribute )  and the attemptNumber is defaulted to 0 
        public Assessment(int lessonId) { this.lessonId = lessonId; this.attemptNumber = 0; }
}
}
