# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy ASP app to Azure Web App - edunest-app
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore NuGet packages
        run: nuget restore WEB_APPLICATION/WEB_APPLICATION.slnx
      - name: Publish to folder
        run: msbuild WEB_APPLICATION/WEB_APPLICATION.slnx /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: '/published/**'
  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3901503ADB264C6599324F35F19721EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C4B552E2E3884528A8F1B8D4DD1F5D27 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_54EB985F59CA47DCB3634F24FC4C48FF }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'edunest-app'
          slot-name: 'Production'
          package: .
